services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data

  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    volumes:
      - .:/store
      - rubygems:/usr/local/bundle
    env_file:
      - .env

  web:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/store
      - rubygems:/usr/local/bundle
    depends_on:
      - db
      - redis
    env_file:
      - .env

  test:
    build: .
    command: bash -c 'bin/rails db:create db:migrate && bundle exec rspec'
    volumes:
      - .:/store
    depends_on:
      - db
      - redis
    env_file:
      - .env.test

volumes:
  postgres13:
  redis_data:
  rubygems:
